Out take
Supernova11567/Robot2021 pull request #5
Opened 2020-10-10 16:07 UTC by godboi524

2020-10-11 07:10 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    }
```suggestion
    public void resetTargets(double in, double currentPosition, double currentTime) {
        this.target = in;
        this.currentPosition = currentPosition;
        this.currentTime = currentTime
    }

```

2020-10-11 07:13 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    }
```suggestion
    public void resetTargets(double in, double startPosition, double startTime) {
        this.target = in;
        this.startPosition = startPosition;
        this.startTime = startTime;
    }

```

2020-10-11 07:14 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +
```suggestion

private double startPosition;
private double startTime;
```

2020-10-11 07:15 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +        double error = target - input;
```suggestion
        double error = target - startPosition - input;

```

2020-10-11 07:15 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    public double OutputForce(double input, double deltaTime) {
```suggestion
    public double OutputForce(double input, double currentTime) {

```

2020-10-11 07:16 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    private double lastError = 0;
```suggestion
    private double lastError = 0;
    private double lastTime

```

2020-10-11 07:16 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +        lastError = error;
```suggestion
        lastError = error;
        lastTime = currentTime;

```

2020-10-11 07:17 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +        integral += error * deltaTime;
```suggestion
        integral += error * (currentTime - lastTime);

```

2020-10-11 07:32 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    public double OutputForce(double input, double deltaTime) {
the delta time should be calculated here and not from where the function called. try give: (double currentPosition, double currentTime).

2020-10-11 07:36 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    public void setTarget(double in) {
you didn't consider the start position of the robot. I will recommend to change this:
```suggestion
    public void resetTargets(double target, double startPosition, double startTime) {

```
and call this function before every time you start calling the outputForce function

2020-10-11 07:37 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +        double delta_e = error - lastError;
the error is the distance from the target, which means you will get here negative value

2020-10-11 07:38 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Constants.java
> +}
why all of this?

2020-10-11 07:40 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +        double velocity = Math.sqrt((d*d*g)/(2*h)+(h*2*g));
didn't consider shooter angle at all?

2020-10-11 07:43 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +}
all of the running code here need to be in "Supernova11567Main". the only things here should be functions (like functionsLibrary)
move it to supernovaMain after you finish

2020-10-11 07:43 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ShootDisc.java
> +}
as I said, In supernova11567Main

2020-10-12 07:30 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Constants.java
> +}
constants. my brother said that it's good to declare constants in a different class

2020-10-12 07:30 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +        double velocity = Math.sqrt((d*d*g)/(2*h)+(h*2*g));
no need

2020-10-12 07:37 UTC, Adam14boat commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +        double delta_e = error - lastError;
No, the error here is for the velocity of the shooter which gets smaller therefore it will be positive

2020-10-12 07:37 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +        double delta_e = error - lastError;
ok

2020-10-12 07:38 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +        double delta_e = error - lastError;
wait no. that's not true. the error gets smaller each time

2020-10-12 07:38 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +        double delta_e = error - lastError;
oh wait. yeah, you're right

2020-10-12 07:41 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    public double OutputForce(double input, double deltaTime) {
but if I calculate it where the function is called, I can use the same deltaTime for other functions where I called the OutputForce, which I did.

2020-10-12 07:41 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    public double OutputForce(double input, double deltaTime) {
after all, we want the same deltaTime, don't we?

2020-10-12 07:44 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    public void setTarget(double in) {
there is no point in reseting the target because it is different for every class that uses the PID

2020-10-12 07:44 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    public void setTarget(double in) {
the start position of the robot is true however

2020-10-12 07:48 UTC, Adam14boat commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    public void setTarget(double in) {
The starting position of the robot is included in the "input" of outputForce, the start time also does not matter all that matters is the delta time.

2020-10-12 07:57 UTC, Adam14boat commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    public void setTarget(double in) {
Therefore what @godboi524 has is fine

2020-10-12 07:58 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    public void setTarget(double in) {
no no. you're incorrect about the startTime, because I need the how much time passed for the certain runtime of a function, not the entire robot. And as to the startPosition, there's no point. Say we have the robot, we want it to move a certain distance, the start position will be the distance to the target anyway. If we have a certain speed we want to get to, I guess the speed of the motor could be higher than 0, but that would be done outside of the PID class so that there won't be a start position for distance.

2020-10-12 08:02 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    public void setTarget(double in) {
Actually no, you wouldn't even need a start speed for the motor. We calculate the difference anyway.

2020-10-12 08:42 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +}
what is supernova11567Main?

2020-10-12 08:43 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ShootDisc.java
> +}
what is supernova11567Main?

2020-10-12 09:17 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +        double velocity = Math.sqrt((d*d*g)/(2*h)+(h*2*g));
or g?

2020-10-12 09:18 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Constants.java
> +}
but I saw you didn't use it in the other files

2020-10-12 09:21 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    public double OutputForce(double input, double deltaTime) {
yahh, but the whole idea of this class is to keep the variables, and if you calculate the delta time there, it means you need variables outside this class, what we don't want.

2020-10-12 09:22 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    public void setTarget(double in) {
do what you think is ok, just make sure the PID calculate is correct at the end

2020-10-12 09:24 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +        double velocity = Math.sqrt((d*d*g)/(2*h)+(h*2*g));
so you are saying that I can shoot at all angle at all star and the velocity will stay the same?

2020-10-12 09:26 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +}
supernova11567Main is the file that run on the robot. all the other is not running, only functions

2020-10-12 09:31 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +        double velocity = Math.sqrt((d*d*g)/(2*h)+(h*2*g));
oh sry didn't see the g

2020-10-12 09:31 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +        double velocity = Math.sqrt((d*d*g)/(2*h)+(h*2*g));
but what about angle?

2020-10-12 14:35 UTC, Adam14boat requested changes

2020-10-12 14:35 UTC, Adam14boat commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Constants.java
> +public class Constants {
Add a class for just Shooter constants

2020-10-12 14:35 UTC, Adam14boat commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PID.java
> +    //sets the target of the pid
Rename in to target

2020-10-12 14:35 UTC, Adam14boat commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +        double position = ticks/ Constants.TICKS_PER_METER;
Format the code

2020-10-12 14:35 UTC, Adam14boat commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +        int ticks = shootMotor.getCurrentPosition() - this.LastPosition;
Names of variables should be camel cased - lastPosition

2020-10-12 14:35 UTC, Adam14boat commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +        return velocity; //self explanatory
Delete unnecessary (self explanatory) comment

2020-10-12 14:35 UTC, Adam14boat commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +        return runtime.seconds() - this.LastTime;
lastTime

2020-10-12 14:35 UTC, Adam14boat commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +    public Shooter() {
You don't need the _this_ before the global variables

2020-10-12 14:42 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Constants.java
> +}
That's just because the only constants we have are for the shooter

2020-10-12 14:44 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +        double velocity = Math.sqrt((d*d*g)/(2*h)+(h*2*g));
it doesn't matter. As long as we assume that the disc will go in at angle 0 there is really no point.

2020-10-12 14:44 UTC, godboi524 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +}
but where is it? It's not there.

2020-10-12 17:55 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Constants.java
> +}
I don't get it if you are saying that you dont use it, and the variables equal to 0, why this file exist

2020-10-12 17:57 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +}
You started this pull request before I added supernovaMain. Lets finish these files and merge and then you can start another that contain supernovaMain

2020-10-12 18:17 UTC, Adam14boat commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +}
I think it is better to merge the main branch into the shooter branch that way all the changes from the master are in the shooter and a new pull request doesn't need to be made

2020-10-12 18:18 UTC, Adam14boat commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Constants.java
> +}
These constants are used for the shooter and as a starting value they are 0

2020-10-13 06:15 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +}
so godboi524 merge main branch into your and fix the bugs

2020-10-14 08:59 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +        double velocity = Math.sqrt((d*d*g)/(2*h)+(h*2*g));
angle 0?

2020-10-14 08:59 UTC, IdanRosenzweig commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +        double velocity = Math.sqrt((d*d*g)/(2*h)+(h*2*g));
you mean theta?

2020-10-14 09:34 UTC, Adam14boat commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +        double velocity = Math.sqrt((d*d*g)/(2*h)+(h*2*g));
The assumption is that the disc enters the goal horizontally (angle of 0)

2020-10-14 09:51 UTC, Adam14boat requested changes

2020-10-14 09:51 UTC, Adam14boat commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Shooter.java
> +    private ElapsedTime runtime = new ElapsedTime();
Move the timer to OpsMode

2020-10-16 18:22 UTC, Adam14boat commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ShootDisc.java
> +public class ShootDisc extends OpMode {
Add @Teleop see OpMode examples

2020-12-22 14:17 UTC, merged